### Setup

```{r}
library(tidyverse)
library(rvest)
library(robotstxt)
```

### Scraping Taylor's Top 100

```{r}
page <- read_html("https://www.billboard.com/artist/taylor-swift/chart-history/hsi/")

name <- page %>%
  html_elements(".a-truncate-ellipsis") %>%
  html_text2()

dates <- page %>%
  html_elements(".c-label__link") %>%
  html_text2()

peak_pos <- page %>%
  html_elements(".artist-chart-row-peak-pos") %>%
  html_text2()

weeks_charting <- page %>%
  html_elements(".artist-chart-row-week-on-chart") %>%
  html_text2()

debut_date <- rep(NA, 231)
peak_date <- rep(NA, 231)

for (i in 1:212) {
  debut_date[i] = dates[(i*2)-1]
  peak_date[i] = dates[i*2]
}

billboard_data <- tibble(
  name = name,
  peak_pos = peak_pos,
  debut_date = debut_date,
  peak_date = peak_date,
  weeks_charting = weeks_charting
)

write.csv(billboard_albums, "billboard_albums.csv")
```

### Scraping Taylor's Top 200

```{r}
billboard_albums <- readr:read.csv("billboard_albums.csv")
billboard_albums <- as_tibble(billboard_albums) %>% filter(!is.na(peak_pos)) %>%
  mutate(X.1 = NULL, X = NULL, X.2 = NULL, X.3 = NULL)
```
