
```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = 'hide')
library(tidyverse)
library(janitor)
library(plotly)
library(RCurl)
# library(taylor)

# install.packages("remotes")
# remotes::install_github("wjakethompson/taylor")

load("taylor_all_songs.rda")
load("taylor_albums.rda")
load("taylor_album_songs.rda")

billboard_albums <- read_csv(
  "/Users/mariahloehr/Stat220/Assignments/final_project/billboard_albums.csv")

billboard_albums[8,2] <- "folklore"
billboard_albums[9,2] <- "evermore"

billboard_songs <- read_csv(
  "/Users/mariahloehr/Stat220/Assignments/final_project/billboard_songs.csv")


# install.packages("tidytuesdayR")
# 
# tuesdata <- tidytuesdayR::tt_load('2023-10-17')

# taylor_album_songs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-10-17/taylor_album_songs.csv')
# taylor_all_songs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-10-17/taylor_all_songs.csv')
# taylor_albums <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-10-17/taylor_albums.csv')

# taylor_album_songs <- tuesdata$taylor_album_songs
# taylor_all_songs <- tuesdata$taylor_all_songs
# taylor_albums <- tuesdata$taylor_albums
```

```{r wrangling}
taylor_album_focus <- taylor_all_songs %>%
  full_join(taylor_albums, by = c("album_name", "ep", "album_release")) %>%
  full_join(explicit_df, by = "album_name") %>%
  inner_join(billboard_albums, by = "album_name") %>%
  filter(!(is.na(album_name))) %>%
  filter(!(album_name %in% c("The Taylor Swift Holiday Collection", "Beautiful Eyes"))) %>%
  mutate(album_name = as.character(album_name)) %>%
  group_by(album_name) %>%
  mutate(album_length_min = sum(duration_ms, na.rm = T)/60000,
         album_danceability = mean(danceability, na.rm = T),
         album_energy = mean(energy, na.rm = T),
         album_loudness = mean(loudness, na.rm = T),
         album_speechiness = mean(speechiness, na.rm = T),
         album_acousticness = mean(acousticness, na.rm = T),
         album_instrumentalness = mean(instrumentalness, na.rm = T),
         album_liveness = mean(liveness, na.rm = T),
         album_valence = mean(valence, na.rm = T),
         album_tempo = mean(tempo, na.rm = T),
         album_track_number = max(track_number),
         album_metacritic_score = metacritic_score,
         album_user_score = user_score,
         album_peak_pos = peak_pos,
         album_weeks_charting = weeks_charting,
         album_number_of_explicit_songs = coalesce(album_number_of_explicit_songs, 0)
         ) %>%
    ungroup()

explicit_df <- taylor_all_songs %>% 
  group_by(album_name) %>% 
  count(explicit) %>%
  filter(explicit == TRUE) %>%
  select(album_name, n)

colnames(explicit_df)[2] <- 'album_number_of_explicit_songs'

full_join(taylor_album_focus, explicit_df, by = "album_name")


sum(as.integer(as.logical(taylor_all_songs$explicit)), na.rm = T)

(taylor_all_songs %>% count(explicit))
 
   # %>% filter(explicit == TRUE))[[2]]

# (taylor_album_focus %>% group_by(album_name) %>% count(mode_name) %>% slice_max(n, n=1))[[2]]
```

```{r song_focus}
taylor_song_focus <- taylor_all_songs %>%
  # full_join(billboard_songs, by = c("track_name" = "name")) %>%
  select(c(1,3:5, 11:29)) %>%
  mutate(duration_ms = duration_ms/60000)

colnames(taylor_song_focus)[18] <- 'duration_min'
```



```{r}
all_album_palette <- c("lightseagreen", 
                       "darkgoldenrod1", 
                       "mediumorchid", 
                       "red", 
                       "lightskyblue", 
                       "black", 
                       "hotpink",  
                       "ivory4", 
                       "darkorange3", 
                       "darkgoldenrod3" ,
                       "red3",
                       "navyblue",
                       "mediumorchid4", 
                       "deepskyblue")


p <- taylor_album_focus %>%
  ggplot() +
  geom_point(aes(x=album_release, y=album_user_score, color = fct_reorder(album_name, album_release), text = paste("Album Release: ", album_release, "<br>Album User Score: ", album_user_score, "<br><b>Album:</b> ", fct_reorder(album_name, album_release))), size = 3) +
  scale_color_manual(values = all_album_palette) +
  labs(color = "Album",
       y = "User Score")

ggplotly(p, tooltip = "text")
```

```{r}
album1 <- "1989 (Taylor's Version)"

paste(str_replace_all(str_replace_all(str_replace_all(album1,"\\s","_"),
                                                      "\\(", ""), "\\)", ""), ".jpg", sep="")
```

```{r color palette}
taylor_palette <- c("Taylor Swift" ="lightseagreen","The Taylor Swift Holiday Collection"="forestgreen", 
  "Beautiful Eyes" ="darkorange", "Fearless" ="darkgoldenrod1",
  "Speak Now" ="mediumorchid", "Red" ="red", 
  "1989" ="cornflowerblue", "reputation" ="black", 
  "Lover" ="hotpink", "folklore" ="ivory4",
  "evermore" ="darkorange3","Fearless (Taylor's Version)"="darkgoldenrod3",
  "Red (Taylor's Version)" ="red3", "Midnights" ="navyblue",
  "Speak Now (Taylor's Version)" ="mediumorchid4",
  "1989 (Taylor's Version)" ="deepskyblue", "NA"="gray99")

typeof(taylor_palette)

ts_colors <- function(x) {
  cols <- c(x)
  if (is.null(cols)){
  return (taylor_palette)}
  taylor_palette[cols]
}

ts_colors(unique(taylor_album_focus$album_name))
```

```{r explicit analysis}
taylor_all_songs %>% ungroup() %>%
  # unnest words into rows
  unnest_tokens(output = text, input = text, drop = F) %>%
  # mutates: make lowercase, remove text column, create new year column after
  # lubridate functions are applied
  mutate(word = str_to_lower(text), text = NULL,
         year = year(mdy(date)), date = NULL) %>%
  # remove stop words with anti-join, group by year and word, then count, remove
  # redundant rows
  anti_join(stop_words) %>% group_by(year, word) %>% mutate(count = n()) %>%
  distinct()
```

